// Copyright 2024 The Concerto Contributors.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: concerto/sample/calc/v1/calc_v1.proto

package calc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Op represents the type of arithmetic operation.
type Op int32

const (
	// Add represents addition operation.
	Op_OP_ADD Op = 0
	// Subtract represents subtraction operation.
	Op_OP_SUBTRACT Op = 1
	// Multiply represents multiplication operation.
	Op_OP_MULTIPLY Op = 2
	// Divide represents division operation.
	Op_OP_DIVIDE Op = 3
)

// Enum value maps for Op.
var (
	Op_name = map[int32]string{
		0: "OP_ADD",
		1: "OP_SUBTRACT",
		2: "OP_MULTIPLY",
		3: "OP_DIVIDE",
	}
	Op_value = map[string]int32{
		"OP_ADD":      0,
		"OP_SUBTRACT": 1,
		"OP_MULTIPLY": 2,
		"OP_DIVIDE":   3,
	}
)

func (x Op) Enum() *Op {
	p := new(Op)
	*p = x
	return p
}

func (x Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op) Descriptor() protoreflect.EnumDescriptor {
	return file_concerto_sample_calc_v1_calc_v1_proto_enumTypes[0].Descriptor()
}

func (Op) Type() protoreflect.EnumType {
	return &file_concerto_sample_calc_v1_calc_v1_proto_enumTypes[0]
}

func (x Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Op.Descriptor instead.
func (Op) EnumDescriptor() ([]byte, []int) {
	return file_concerto_sample_calc_v1_calc_v1_proto_rawDescGZIP(), []int{0}
}

type CalculateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op   Op    `protobuf:"varint,1,opt,name=op,proto3,enum=concerto.sample.calc.v1.Op" json:"op,omitempty"`
	Num1 int64 `protobuf:"varint,2,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2 int64 `protobuf:"varint,3,opt,name=num2,proto3" json:"num2,omitempty"`
}

func (x *CalculateRequest) Reset() {
	*x = CalculateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_concerto_sample_calc_v1_calc_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRequest) ProtoMessage() {}

func (x *CalculateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_concerto_sample_calc_v1_calc_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRequest.ProtoReflect.Descriptor instead.
func (*CalculateRequest) Descriptor() ([]byte, []int) {
	return file_concerto_sample_calc_v1_calc_v1_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateRequest) GetOp() Op {
	if x != nil {
		return x.Op
	}
	return Op_OP_ADD
}

func (x *CalculateRequest) GetNum1() int64 {
	if x != nil {
		return x.Num1
	}
	return 0
}

func (x *CalculateRequest) GetNum2() int64 {
	if x != nil {
		return x.Num2
	}
	return 0
}

type CalculateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int64 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CalculateResponse) Reset() {
	*x = CalculateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_concerto_sample_calc_v1_calc_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateResponse) ProtoMessage() {}

func (x *CalculateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_concerto_sample_calc_v1_calc_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateResponse.ProtoReflect.Descriptor instead.
func (*CalculateResponse) Descriptor() ([]byte, []int) {
	return file_concerto_sample_calc_v1_calc_v1_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_concerto_sample_calc_v1_calc_v1_proto protoreflect.FileDescriptor

var file_concerto_sample_calc_v1_calc_v1_proto_rawDesc = []byte{
	0x0a, 0x25, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x72, 0x74, 0x6f, 0x2f, 0x73, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x5f, 0x76,
	0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x72, 0x74,
	0x6f, 0x2e, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x76, 0x31,
	0x22, 0x6f, 0x0a, 0x10, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x72, 0x74, 0x6f, 0x2e, 0x73, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x52, 0x02, 0x6f,
	0x70, 0x12, 0x16, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x42,
	0x02, 0x30, 0x01, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x31, 0x12, 0x16, 0x0a, 0x04, 0x6e, 0x75, 0x6d,
	0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x42, 0x02, 0x30, 0x01, 0x52, 0x04, 0x6e, 0x75, 0x6d,
	0x32, 0x22, 0x2f, 0x0a, 0x11, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x02, 0x30, 0x01, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x2a, 0x41, 0x0a, 0x02, 0x4f, 0x70, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x50, 0x5f, 0x41,
	0x44, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4f, 0x50, 0x5f, 0x53, 0x55, 0x42, 0x54, 0x52,
	0x41, 0x43, 0x54, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4f, 0x50, 0x5f, 0x4d, 0x55, 0x4c, 0x54,
	0x49, 0x50, 0x4c, 0x59, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x50, 0x5f, 0x44, 0x49, 0x56,
	0x49, 0x44, 0x45, 0x10, 0x03, 0x32, 0x79, 0x0a, 0x11, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x64, 0x0a, 0x09, 0x43, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x29, 0x2e, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x72,
	0x74, 0x6f, 0x2e, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x72, 0x74, 0x6f, 0x2e, 0x73, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x5d, 0x5a, 0x5b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67,
	0x6f, 0x72, 0x68, 0x79, 0x74, 0x68, 0x6d, 0x2f, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x72, 0x74, 0x6f,
	0x2f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x2f, 0x63, 0x6f, 0x6e,
	0x63, 0x65, 0x72, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x65, 0x6e, 0x2d,
	0x67, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x72, 0x74, 0x6f, 0x2f, 0x73, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x61, 0x6c, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_concerto_sample_calc_v1_calc_v1_proto_rawDescOnce sync.Once
	file_concerto_sample_calc_v1_calc_v1_proto_rawDescData = file_concerto_sample_calc_v1_calc_v1_proto_rawDesc
)

func file_concerto_sample_calc_v1_calc_v1_proto_rawDescGZIP() []byte {
	file_concerto_sample_calc_v1_calc_v1_proto_rawDescOnce.Do(func() {
		file_concerto_sample_calc_v1_calc_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_concerto_sample_calc_v1_calc_v1_proto_rawDescData)
	})
	return file_concerto_sample_calc_v1_calc_v1_proto_rawDescData
}

var file_concerto_sample_calc_v1_calc_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_concerto_sample_calc_v1_calc_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_concerto_sample_calc_v1_calc_v1_proto_goTypes = []interface{}{
	(Op)(0),                   // 0: concerto.sample.calc.v1.Op
	(*CalculateRequest)(nil),  // 1: concerto.sample.calc.v1.CalculateRequest
	(*CalculateResponse)(nil), // 2: concerto.sample.calc.v1.CalculateResponse
}
var file_concerto_sample_calc_v1_calc_v1_proto_depIdxs = []int32{
	0, // 0: concerto.sample.calc.v1.CalculateRequest.op:type_name -> concerto.sample.calc.v1.Op
	1, // 1: concerto.sample.calc.v1.CalculatorService.Calculate:input_type -> concerto.sample.calc.v1.CalculateRequest
	2, // 2: concerto.sample.calc.v1.CalculatorService.Calculate:output_type -> concerto.sample.calc.v1.CalculateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_concerto_sample_calc_v1_calc_v1_proto_init() }
func file_concerto_sample_calc_v1_calc_v1_proto_init() {
	if File_concerto_sample_calc_v1_calc_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_concerto_sample_calc_v1_calc_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_concerto_sample_calc_v1_calc_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_concerto_sample_calc_v1_calc_v1_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_concerto_sample_calc_v1_calc_v1_proto_goTypes,
		DependencyIndexes: file_concerto_sample_calc_v1_calc_v1_proto_depIdxs,
		EnumInfos:         file_concerto_sample_calc_v1_calc_v1_proto_enumTypes,
		MessageInfos:      file_concerto_sample_calc_v1_calc_v1_proto_msgTypes,
	}.Build()
	File_concerto_sample_calc_v1_calc_v1_proto = out.File
	file_concerto_sample_calc_v1_calc_v1_proto_rawDesc = nil
	file_concerto_sample_calc_v1_calc_v1_proto_goTypes = nil
	file_concerto_sample_calc_v1_calc_v1_proto_depIdxs = nil
}
